"""接口层数据模型（请求体 / 响应体 / MQ 载体）集中导出。"""

from app.models.schemas.audit import AuditSourceInfo
from app.models.schemas.avatar_audit import (
    AvatarAuditApproveReq,
    AvatarAuditItem,
    AvatarAuditListResp,
    AvatarAuditMineResp,
    AvatarAuditRejectReq,
)
from app.models.schemas.ban import (
    BanCreateReq,
    BanItem,
    BanListResp,
    BanStatusResp,
    UnbanReq,
)
from app.models.schemas.comment import (
    CommentActionReq,
    CommentActionResp,
    CommentAddReq,
    CommentAddResp,
    CommentAuditItem,
    CommentAuditListResp,
    CommentAuditReq,
    CommentAuditResp,
    CommentBulkAuditReq,
    CommentBulkAuditResp,
    CommentCountResp,
    CommentDelReq,
    CommentItem,
    CommentListResp,
    CommentOperationResp,
    CommentReportReq,
    CommentReportResp,
    CommentSourceResp,
    CommentStatsResp,
    CommentSubListResp,
    CommentTopReq,
    CommentTopResp,
    CommentUserBrief,
)
from app.models.schemas.dm import (
    DmAckReq,
    DmAuditItem,
    DmAuditListResp,
    DmAuditReq,
    DmBulkAuditReq,
    DmBulkAuditResp,
    DmDeleteReq,
    DmMessageItem,
    DmMessageListResp,
    DmOperationResp,
    DmRecallReq,
    DmSendReq,
    DmSendResp,
    DmSessionContextResp,
    DmSessionDeleteReq,
    DmSessionItem,
    DmSessionListResp,
    DmStatsResp,
    DmTopReq,
    DmTopResp,
)
from app.models.schemas.favorite import (
    FavoriteAddReq,
    FavoriteAddResp,
    FavoriteDynFoldersResp,
    FavoriteFolderCreateReq,
    FavoriteFolderDeleteReq,
    FavoriteFolderResp,
    FavoriteFolderUpdateReq,
    FavoriteItemListResp,
    FavoriteListItem,
    FavoriteListReq,
    FavoriteListResp,
    FavoriteRemoveReq,
    FavoriteSettingReq,
    FavoriteSettingResp,
)
from app.models.schemas.folder_cover_audit import (
    FolderCoverAuditApproveReq,
    FolderCoverAuditItem,
    FolderCoverAuditListResp,
    FolderCoverAuditMineResp,
    FolderCoverAuditRejectReq,
)
from app.models.schemas.interaction import InteractionStatusItem, InteractionStatusResp
from app.models.schemas.event import (
    EventAggregateItem,
    EventAggregateResp,
    EventItem,
    EventListResp,
    EventMsgfeedContent,
    EventMsgfeedCursor,
    EventMsgfeedItem,
    EventMsgfeedSection,
    EventReadReq,
    EventReadResp,
    EventReportReq,
    EventReportResp,
    EventUnreadResp,
    EventUserBrief,
)
from app.models.schemas.follow import (
    BlockReq,
    FollowCountResp,
    FollowListItem,
    FollowListResp,
    FollowOpResp,
    FollowRelationResp,
    FollowReq,
)
from app.models.schemas.mq import (
    DmContentPayload,
    DmNotifyPayload,
    EventPushPayload,
    InteractionViewPayload,
    NotifyPushPayload,
    UserDeactivatePayload,
)
from app.models.schemas.notify import (
    BiliSystemNotifyResp,
    NotifyAdminItem,
    NotifyAdminListResp,
    NotifyCreateReq,
    NotifyDeleteReq,
    NotifyItem,
    NotifyListResp,
    NotifyPullResp,
    NotifyUpdateReq,
    SystemNotifyItem,
    SystemNotifyListResp,
)
from app.models.schemas.setting import (
    MessageSettingResp,
    MessageSettingUpdateReq,
    UserActivityResp,
)
from app.models.schemas.space import (
    SpaceFollowStat,
    SpaceInfoResp,
    SpaceOfficial,
    SpaceUpStat,
    SpaceVip,
    SpaceVipLabel,
    SpaceVipWrap,
)
from app.models.schemas.report import (
    ReportCreateReq,
    ReportItem,
    ReportListResp,
    ReportReviewReq,
)
from app.models.schemas.user_brief import (
    UserBriefOut,
)
from app.models.schemas.visibility import (
    Private,
    VisibilityMixin,
)
from app.models.schemas.user_records import (
    UserActLogItem,
    UserActLogListResp,
    UserExpRecordItem,
    UserExpRecordListResp,
)

__all__ = [
    # 审核通用
    "AuditSourceInfo",
    "AvatarAuditApproveReq",
    "AvatarAuditItem",
    "AvatarAuditListResp",
    # 头像更换审核
    "AvatarAuditMineResp",
    "AvatarAuditRejectReq",
    # 用户封禁（审核联动）
    "BanCreateReq",
    "BanItem",
    "BanListResp",
    "BanStatusResp",
    "BiliSystemNotifyResp",
    "BlockReq",
    "CommentActionReq",
    "CommentActionResp",
    "CommentAddReq",
    "CommentAddResp",
    "CommentAuditItem",
    "CommentAuditListResp",
    "CommentAuditReq",
    "CommentAuditResp",
    "CommentBulkAuditReq",
    "CommentBulkAuditResp",
    "CommentCountResp",
    "CommentDelReq",
    "CommentItem",
    "CommentListResp",
    "CommentOperationResp",
    "CommentReportReq",
    "CommentReportResp",
    "CommentSourceResp",
    "CommentStatsResp",
    "CommentSubListResp",
    "CommentTopReq",
    "CommentTopResp",
    # 评论
    "CommentUserBrief",
    "DmAckReq",
    "DmAuditItem",
    "DmAuditListResp",
    "DmAuditReq",
    "DmBulkAuditReq",
    "DmBulkAuditResp",
    # MQ 载体
    "DmContentPayload",
    "DmDeleteReq",
    "InteractionViewPayload",
    "UserDeactivatePayload",
    "DmMessageItem",
    "DmMessageListResp",
    "DmNotifyPayload",
    "DmOperationResp",
    "DmRecallReq",
    # 私信
    "DmSendReq",
    "DmSendResp",
    "DmSessionContextResp",
    "DmSessionDeleteReq",
    "DmSessionItem",
    "DmSessionListResp",
    "DmStatsResp",
    "DmTopReq",
    "DmTopResp",
    # 收藏
    "FavoriteAddReq",
    "FavoriteAddResp",
    "FavoriteDynFoldersResp",
    "FavoriteFolderCreateReq",
    "FavoriteFolderDeleteReq",
    "FavoriteFolderResp",
    "FavoriteFolderUpdateReq",
    "FavoriteItemListResp",
    "FavoriteListItem",
    "FavoriteListReq",
    "FavoriteListResp",
    "FavoriteRemoveReq",
    "FavoriteSettingReq",
    "FavoriteSettingResp",
    # 收藏夹封面审核（2.28.0）
    "FolderCoverAuditApproveReq",
    "FolderCoverAuditItem",
    "FolderCoverAuditListResp",
    "FolderCoverAuditMineResp",
    "FolderCoverAuditRejectReq",
    # 多业务资源交互（2.17.0）
    "InteractionStatusItem",
    "InteractionStatusResp",
    "EventAggregateItem",
    "EventAggregateResp",
    "EventItem",
    "EventListResp",
    "EventMsgfeedContent",
    "EventMsgfeedCursor",
    "EventMsgfeedItem",
    "EventMsgfeedSection",
    "EventPushPayload",
    "EventReadReq",
    "EventReadResp",
    # 事件提醒
    "EventReportReq",
    "EventReportResp",
    "EventUnreadResp",
    "EventUserBrief",
    "FollowCountResp",
    "FollowListItem",
    "FollowListResp",
    "FollowOpResp",
    "FollowRelationResp",
    # 用户关注 / 拉黑
    "FollowReq",
    # 消息设置
    "MessageSettingResp",
    "MessageSettingUpdateReq",
    "NotifyAdminItem",
    "NotifyAdminListResp",
    # 系统通知
    "NotifyCreateReq",
    "NotifyDeleteReq",
    "NotifyItem",
    "NotifyListResp",
    "NotifyPullResp",
    "NotifyPushPayload",
    "NotifyUpdateReq",
    "SystemNotifyItem",
    "SystemNotifyListResp",
    # 用户空间信息
    "SpaceFollowStat",
    "SpaceInfoResp",
    "SpaceOfficial",
    "SpaceUpStat",
    "SpaceVip",
    "SpaceVipLabel",
    "SpaceVipWrap",
    # 统一举报（2.14.0）
    "ReportCreateReq",
    "ReportItem",
    "ReportListResp",
    "ReportReviewReq",
    "UnbanReq",
    "UserActLogItem",
    # 用户展示简档：单一输出模型（§5.12）
    "UserBriefOut",
    # 字段级可见性：标记 + 序列化期裁剪 mixin（§5.12）
    "Private",
    "VisibilityMixin",
    "UserActLogListResp",
    "UserActivityResp",
    "UserExpRecordItem",
    "UserExpRecordListResp",
]
