"""empty message

Revision ID: 8cc8a183fe02
Revises: 
Create Date: 2026-08-29 22:25:52.887364

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc8a183fe02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TFavoriteFolder',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('folder_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_default', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('folder_id', name='TFavoriteFolder_pkey'),
    comment='动态收藏夹：每用户多夹，一个默认夹'
    )
    op.create_index('idx_fav_folder_mid_created', 'TFavoriteFolder', ['mid', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_TFavoriteFolder_created_at'), 'TFavoriteFolder', ['created_at'], unique=False)
    op.create_index(op.f('ix_TFavoriteFolder_mid'), 'TFavoriteFolder', ['mid'], unique=False)
    op.create_table('TFolderCoverAudit',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('folderId', sa.BIGINT(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('oldCover', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('newCover', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('auditStatus', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='foldercoverauditstatusenum'), nullable=False),
    sa.Column('auditOperatorMid', sa.BIGINT(), nullable=True),
    sa.Column('auditReason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('auditedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk', name='TFolderCoverAudit_pkey'),
    comment='收藏夹封面审核：pending/approved/rejected，通过后写入 cover_url'
    )
    op.create_index('idx_folder_cover_audit_folder_status', 'TFolderCoverAudit', ['folderId', 'auditStatus'], unique=False)
    op.create_index('idx_folder_cover_audit_status_created', 'TFolderCoverAudit', ['auditStatus', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_TFolderCoverAudit_created_at'), 'TFolderCoverAudit', ['created_at'], unique=False)
    op.create_table('TInteractionStat',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('bizType', sa.Enum('DYNAMIC', 'LOTTERY', 'RPA_ACTION', 'RPA_WORKFLOW', 'RPA_BROWSER', 'RPA_PLUGIN', name='interactionbiztypeenum'), autoincrement=False, nullable=False),
    sa.Column('bizId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('likeCount', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('favoriteCount', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('viewCount', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('commentCount', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('repostCount', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('shareCount', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('dislikeCount', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('coinCount', sa.BIGINT(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('bizType', 'bizId', name='TInteractionStat_pkey'),
    comment='通用交互计数：非动态资源(bizType,bizId)的收藏/点赞/浏览计数'
    )
    op.create_index(op.f('ix_TInteractionStat_created_at'), 'TInteractionStat', ['created_at'], unique=False)
    op.create_table('TInteractionViewLog',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bizType', sa.Enum('DYNAMIC', 'LOTTERY', 'RPA_ACTION', 'RPA_WORKFLOW', 'RPA_BROWSER', 'RPA_PLUGIN', name='interactionbiztypeenum'), nullable=False),
    sa.Column('bizId', sa.BIGINT(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('viewCount', sa.Integer(), nullable=False),
    sa.Column('lastViewAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('pk', name='TInteractionViewLog_pkey'),
    sa.UniqueConstraint('bizType', 'bizId', 'mid', name='TInteractionViewLog_bizType_bizId_mid_key'),
    comment='通用浏览去重表：每用户每资源一行，lastViewAt 判自然日窗口'
    )
    op.create_index(op.f('ix_TInteractionViewLog_created_at'), 'TInteractionViewLog', ['created_at'], unique=False)
    op.create_table('TMoment',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dynId', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('dynType', sa.Enum('FORWARD', 'WORD', name='momenttypeenum'), nullable=False),
    sa.Column('bizRid', sa.BIGINT(), nullable=True),
    sa.Column('bizType', sa.Enum('DYNAMIC', 'LOTTERY', 'RPA_ACTION', 'RPA_WORKFLOW', 'RPA_BROWSER', 'RPA_PLUGIN', name='interactionbiztypeenum'), nullable=True),
    sa.Column('contentText', sa.Text(), nullable=True),
    sa.Column('contentJson', sa.JSON(), nullable=False),
    sa.Column('repostSrcDynId', sa.BIGINT(), nullable=True),
    sa.Column('repostDepth', sa.Integer(), nullable=False),
    sa.Column('topicId', sa.BIGINT(), nullable=True),
    sa.Column('lbsPoi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('lbsLat', sa.Float(), nullable=True),
    sa.Column('lbsLng', sa.Float(), nullable=True),
    sa.Column('ipLocation', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ipIsp', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('visibleScope', sa.Enum('PUBLIC', 'FOLLOWER', 'SELF', 'CHARGE', name='momentvisiblescopeenum'), nullable=False),
    sa.Column('closeComment', sa.Integer(), nullable=False),
    sa.Column('upChooseComment', sa.Integer(), nullable=False),
    sa.Column('foldType', sa.Enum('NONE', 'USER_FOLD', 'OVER_FREQ_FOLD', name='momentfoldtypeenum'), nullable=False),
    sa.Column('auditStatus', sa.Enum('AUDITING', 'NORMAL', 'REJECTED', 'HIDDEN', name='momentauditstatusenum'), nullable=False),
    sa.Column('auditRejectReason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('isTop', sa.Integer(), nullable=False),
    sa.Column('topTime', sa.DateTime(), nullable=True),
    sa.Column('timerPubTime', sa.DateTime(), nullable=True),
    sa.Column('pubTime', sa.DateTime(), nullable=True),
    sa.Column('deletedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repostSrcDynId'], ['TMoment.dynId'], name='TMoment_repostSrcDynId_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('dynId', name='TMoment_pkey'),
    comment='动态主表：WORD 文字 / FORWARD 转发，MVP 不含图片上传（正文外链图）'
    )
    op.create_index('idx_dynamic_auditing_created', 'TMoment', ['auditStatus', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_dynamic_biz', 'TMoment', ['bizType', 'bizRid'], unique=False)
    op.create_index('idx_dynamic_mid_created', 'TMoment', ['mid', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_dynamic_mid_pubtime', 'TMoment', ['mid', sa.literal_column('pubTime DESC')], unique=False)
    op.create_index('idx_dynamic_pubtime_visible', 'TMoment', [sa.literal_column('pubTime DESC'), 'visibleScope'], unique=False)
    op.create_index('idx_dynamic_repost_src', 'TMoment', ['repostSrcDynId', 'auditStatus'], unique=False)
    op.create_index('idx_dynamic_topic_pubtime', 'TMoment', ['topicId', sa.literal_column('pubTime DESC')], unique=False)
    op.create_index(op.f('ix_TMoment_created_at'), 'TMoment', ['created_at'], unique=False)
    op.create_table('TMomentFavorite',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bizType', sa.Enum('DYNAMIC', 'LOTTERY', 'RPA_ACTION', 'RPA_WORKFLOW', 'RPA_BROWSER', 'RPA_PLUGIN', name='interactionbiztypeenum'), nullable=False),
    sa.Column('bizId', sa.BIGINT(), nullable=False),
    sa.Column('dynId', sa.BIGINT(), nullable=True),
    sa.Column('folderId', sa.BIGINT(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.PrimaryKeyConstraint('pk', name='TMomentFavorite_pkey'),
    sa.UniqueConstraint('bizType', 'bizId', 'folderId', name='TMomentFavorite_bizType_bizId_folderId_key'),
    comment='收藏明细：唯一约束(bizType,bizId,folderId)防重复收藏'
    )
    op.create_index('idx_fav_biz', 'TMomentFavorite', ['bizType', 'bizId'], unique=False)
    op.create_index('idx_fav_folder_created', 'TMomentFavorite', ['folderId', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_fav_mid_created', 'TMomentFavorite', ['mid', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_TMomentFavorite_created_at'), 'TMomentFavorite', ['created_at'], unique=False)
    op.create_index(op.f('ix_TMomentFavorite_dynId'), 'TMomentFavorite', ['dynId'], unique=False)
    op.create_index(op.f('ix_TMomentFavorite_folderId'), 'TMomentFavorite', ['folderId'], unique=False)
    op.create_index(op.f('ix_TMomentFavorite_mid'), 'TMomentFavorite', ['mid'], unique=False)
    op.create_table('TMomentTopic',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('topicId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('topicName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('topicCover', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('topicDesc', sa.Text(), nullable=True),
    sa.Column('jumpUrl', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('dynCount', sa.BIGINT(), nullable=False),
    sa.Column('viewCount', sa.BIGINT(), nullable=False),
    sa.Column('isHot', sa.Integer(), nullable=False),
    sa.Column('sortWeight', sa.Integer(), nullable=False),
    sa.Column('creatorMid', sa.BIGINT(), nullable=False),
    sa.Column('auditStatus', sa.Enum('AUDITING', 'NORMAL', 'REJECTED', name='momenttopicauditstatusenum'), nullable=False),
    sa.Column('auditRejectReason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('pubTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('topicId', name='TMomentTopic_pkey'),
    sa.UniqueConstraint('topicName', name='TMomentTopic_topicName_key'),
    comment='动态话题表：话题广场列表、话题下动态计数、用户创建话题审核等'
    )
    op.create_index('idx_topic_audit_created', 'TMomentTopic', ['auditStatus', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_topic_creator_created', 'TMomentTopic', ['creatorMid', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_TMomentTopic_created_at'), 'TMomentTopic', ['created_at'], unique=False)
    op.create_table('TResourceFeed',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('bizType', sa.Enum('DYNAMIC', 'LOTTERY', 'RPA_ACTION', 'RPA_WORKFLOW', 'RPA_BROWSER', 'RPA_PLUGIN', name='interactionbiztypeenum'), autoincrement=False, nullable=False),
    sa.Column('bizId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=True),
    sa.Column('pubTime', sa.DateTime(), nullable=True),
    sa.Column('auditStatus', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('visibleScope', sa.Enum('PUBLIC', 'FOLLOWER', 'SELF', 'CHARGE', name='momentvisiblescopeenum'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('deletedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bizType', 'bizId', name='TResourceFeed_pkey'),
    comment='通用资源 Feed 元数据：bizType+bizId 统一入 Feed 的排序元数据'
    )
    op.create_index('idx_resfeed_mid_pubtime', 'TResourceFeed', ['mid', sa.literal_column('pubTime DESC')], unique=False)
    op.create_index('idx_resfeed_status_pubtime', 'TResourceFeed', ['auditStatus', sa.literal_column('pubTime DESC')], unique=False)
    op.create_index(op.f('ix_TResourceFeed_created_at'), 'TResourceFeed', ['created_at'], unique=False)
    op.create_table('TResourceReport',
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bizType', sa.Integer(), nullable=False),
    sa.Column('bizId', sa.BIGINT(), nullable=False),
    sa.Column('resourceType', sa.BIGINT(), nullable=True),
    sa.Column('accusedMid', sa.BIGINT(), nullable=False),
    sa.Column('reportMid', sa.BIGINT(), nullable=False),
    sa.Column('reasonType', sa.Integer(), nullable=False),
    sa.Column('reasonDesc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('pics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auditStatus', sa.Integer(), nullable=False),
    sa.Column('auditRemark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('auditAdminMid', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('reportMid', 'bizType', 'bizId', name='TResourceReport_reportMid_bizType_bizId_key'),
    comment='通用资源举报表：任意资源(bizType+bizId)可举报（继承 ReportBase）'
    )
    op.create_index('idx_tresource_report_biz', 'TResourceReport', ['bizType', 'bizId'], unique=False)
    op.create_index(op.f('ix_TResourceReport_bizId'), 'TResourceReport', ['bizId'], unique=False)
    op.create_index(op.f('ix_TResourceReport_bizType'), 'TResourceReport', ['bizType'], unique=False)
    op.create_index(op.f('ix_TResourceReport_reportMid'), 'TResourceReport', ['reportMid'], unique=False)
    op.create_index(op.f('ix_TResourceReport_resourceType'), 'TResourceReport', ['resourceType'], unique=False)
    op.create_table('TUserAvatarAudit',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('oldAvatar', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('newAvatar', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('auditStatus', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='avatarauditstatusenum'), nullable=False),
    sa.Column('auditOperatorMid', sa.BIGINT(), nullable=True),
    sa.Column('auditReason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('auditedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk', name='TUserAvatarAudit_pkey'),
    comment='头像更换审核：pending/approved/rejected，通过后写入公开头像'
    )
    op.create_index('idx_avatar_audit_mid_created', 'TUserAvatarAudit', ['mid', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_avatar_audit_status_created', 'TUserAvatarAudit', ['auditStatus', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_TUserAvatarAudit_created_at'), 'TUserAvatarAudit', ['created_at'], unique=False)
    op.create_table('TUserFavoriteSetting',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('showFavorites', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('mid', name='TUserFavoriteSetting_pkey'),
    comment='用户主页收藏可见性设置：每用户一行'
    )
    op.create_index(op.f('ix_TUserFavoriteSetting_created_at'), 'TUserFavoriteSetting', ['created_at'], unique=False)
    op.create_table('TUserReport',
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bizType', sa.Integer(), nullable=False),
    sa.Column('bizId', sa.BIGINT(), nullable=False),
    sa.Column('resourceType', sa.BIGINT(), nullable=True),
    sa.Column('accusedMid', sa.BIGINT(), nullable=False),
    sa.Column('reportMid', sa.BIGINT(), nullable=False),
    sa.Column('reasonType', sa.Integer(), nullable=False),
    sa.Column('reasonDesc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('pics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auditStatus', sa.Integer(), nullable=False),
    sa.Column('auditRemark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('auditAdminMid', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('reportMid', 'bizType', 'bizId', name='TUserReport_reportMid_bizType_bizId_key'),
    comment='用户空间举报表：bizType=user，bizId=mid（继承 ReportBase）'
    )
    op.create_index('idx_tuser_report_biz', 'TUserReport', ['bizType', 'bizId'], unique=False)
    op.create_index(op.f('ix_TUserReport_bizId'), 'TUserReport', ['bizId'], unique=False)
    op.create_index(op.f('ix_TUserReport_bizType'), 'TUserReport', ['bizType'], unique=False)
    op.create_index(op.f('ix_TUserReport_reportMid'), 'TUserReport', ['reportMid'], unique=False)
    op.create_index(op.f('ix_TUserReport_resourceType'), 'TUserReport', ['resourceType'], unique=False)
    op.create_table('moment_author_quality',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('avgEngagement', sa.Float(), nullable=False),
    sa.Column('recentPublishCount', sa.Integer(), nullable=False),
    sa.Column('violationCount', sa.Integer(), nullable=False),
    sa.Column('fansCount', sa.BIGINT(), nullable=False),
    sa.Column('currentLevel', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('mid', name='moment_author_quality_pkey'),
    comment='作者质量聚合：平均互动率/近7天发布量/违规数'
    )
    op.create_index(op.f('ix_moment_author_quality_created_at'), 'moment_author_quality', ['created_at'], unique=False)
    op.create_table('msg_admin',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('granted_by', sa.BIGINT(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', name='uq_msg_admin_mid')
    )
    op.create_index(op.f('ix_msg_admin_created_at'), 'msg_admin', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_admin_mid'), 'msg_admin', ['mid'], unique=False)
    op.create_table('msg_comment_action',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpid', sa.BIGINT(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('action', sa.Enum('NONE', 'LIKE', 'HATE', name='commentactionenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rpid', 'mid', name='uq_comment_action_rpid_mid')
    )
    op.create_index(op.f('ix_msg_comment_action_action'), 'msg_comment_action', ['action'], unique=False)
    op.create_index(op.f('ix_msg_comment_action_created_at'), 'msg_comment_action', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_comment_action_mid'), 'msg_comment_action', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_comment_action_rpid'), 'msg_comment_action', ['rpid'], unique=False)
    op.create_table('msg_comment_at',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpid', sa.BIGINT(), nullable=False),
    sa.Column('oid', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('DYNAMIC', 'ARTICLE', 'LOTTERY', 'FEEDBACK', 'OTHER', name='commenttypeenum'), nullable=False),
    sa.Column('from_mid', sa.BIGINT(), nullable=False),
    sa.Column('at_mid', sa.BIGINT(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rpid', 'at_mid', name='uq_comment_at_rpid_at_mid')
    )
    op.create_index('idx_comment_at_pending', 'msg_comment_at', ['notified', 'id'], unique=False)
    op.create_index(op.f('ix_msg_comment_at_at_mid'), 'msg_comment_at', ['at_mid'], unique=False)
    op.create_index(op.f('ix_msg_comment_at_created_at'), 'msg_comment_at', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_comment_at_rpid'), 'msg_comment_at', ['rpid'], unique=False)
    op.create_table('msg_comment_content',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rpid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('pictures', sa.JSON(), nullable=False),
    sa.Column('at_mids', sa.JSON(), nullable=False),
    sa.Column('emote_meta', sa.JSON(), nullable=True),
    sa.Column('ip_v4', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('ip_v6', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('ip_location', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('ip_isp', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('plat', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.PrimaryKeyConstraint('rpid')
    )
    op.create_index(op.f('ix_msg_comment_content_created_at'), 'msg_comment_content', ['created_at'], unique=False)
    op.create_table('msg_comment_index',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rpid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('oid', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('DYNAMIC', 'ARTICLE', 'LOTTERY', 'FEEDBACK', 'OTHER', name='commenttypeenum'), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('root', sa.BIGINT(), nullable=False),
    sa.Column('parent', sa.BIGINT(), nullable=False),
    sa.Column('dialog', sa.BIGINT(), nullable=False),
    sa.Column('reply_to_mid', sa.BIGINT(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('hate_count', sa.Integer(), nullable=False),
    sa.Column('rcount', sa.Integer(), nullable=False),
    sa.Column('hot_score', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('NORMAL', 'AUDITING', 'REJECTED', 'HIDDEN', 'DELETED', name='commentstateenum'), nullable=False),
    sa.Column('attr', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rpid')
    )
    op.create_index('idx_comment_hot', 'msg_comment_index', ['oid', 'type', 'root', 'state', 'hot_score', 'rpid'], unique=False)
    op.create_index('idx_comment_sub', 'msg_comment_index', ['root', 'state', 'rpid'], unique=False)
    op.create_index('idx_comment_time', 'msg_comment_index', ['oid', 'type', 'root', 'state', 'rpid'], unique=False)
    op.create_index('idx_comment_user', 'msg_comment_index', ['mid', 'rpid'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_created_at'), 'msg_comment_index', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_dialog'), 'msg_comment_index', ['dialog'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_hot_score'), 'msg_comment_index', ['hot_score'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_mid'), 'msg_comment_index', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_oid'), 'msg_comment_index', ['oid'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_root'), 'msg_comment_index', ['root'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_state'), 'msg_comment_index', ['state'], unique=False)
    op.create_table('msg_comment_report',
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bizType', sa.Integer(), nullable=False),
    sa.Column('bizId', sa.BIGINT(), nullable=False),
    sa.Column('resourceType', sa.BIGINT(), nullable=True),
    sa.Column('accusedMid', sa.BIGINT(), nullable=False),
    sa.Column('reportMid', sa.BIGINT(), nullable=False),
    sa.Column('reasonType', sa.Integer(), nullable=False),
    sa.Column('reasonDesc', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('pics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auditStatus', sa.Integer(), nullable=False),
    sa.Column('auditRemark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('auditAdminMid', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('reportMid', 'bizType', 'bizId', name='uq_comment_report_report_mid_biz_type_biz_id'),
    comment='评论举报表：bizType=comment，bizId=rpid（继承 ReportBase）'
    )
    op.create_index('idx_comment_report_biz', 'msg_comment_report', ['bizType', 'bizId'], unique=False)
    op.create_index(op.f('ix_msg_comment_report_bizId'), 'msg_comment_report', ['bizId'], unique=False)
    op.create_index(op.f('ix_msg_comment_report_bizType'), 'msg_comment_report', ['bizType'], unique=False)
    op.create_index(op.f('ix_msg_comment_report_reportMid'), 'msg_comment_report', ['reportMid'], unique=False)
    op.create_index(op.f('ix_msg_comment_report_resourceType'), 'msg_comment_report', ['resourceType'], unique=False)
    op.create_table('msg_comment_subject',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oid', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('DYNAMIC', 'ARTICLE', 'LOTTERY', 'FEEDBACK', 'OTHER', name='commenttypeenum'), nullable=False),
    sa.Column('up_mid', sa.BIGINT(), nullable=False),
    sa.Column('root_count', sa.Integer(), nullable=False),
    sa.Column('all_count', sa.Integer(), nullable=False),
    sa.Column('floor_seq', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('NORMAL', 'CLOSED', name='commentsubjectstateenum'), nullable=False),
    sa.Column('top_rpid', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oid', 'type', name='uq_comment_subject_oid_type')
    )
    op.create_index(op.f('ix_msg_comment_subject_created_at'), 'msg_comment_subject', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_comment_subject_oid'), 'msg_comment_subject', ['oid'], unique=False)
    op.create_index(op.f('ix_msg_comment_subject_state'), 'msg_comment_subject', ['state'], unique=False)
    op.create_index(op.f('ix_msg_comment_subject_up_mid'), 'msg_comment_subject', ['up_mid'], unique=False)
    op.create_table('msg_dm_content_dlq',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msgkey', sa.BIGINT(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sender_uid', sa.BIGINT(), nullable=False),
    sa.Column('receiver_uid', sa.BIGINT(), nullable=False),
    sa.Column('msg_type', sa.Enum('TEXT', 'IMAGE', 'SYSTEM', name='dmmsgtypeenum'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('msg_ts', sa.BIGINT(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msgkey', name='uq_dm_dlq_msgkey')
    )
    op.create_index(op.f('ix_msg_dm_content_dlq_created_at'), 'msg_dm_content_dlq', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_dm_content_dlq_msgkey'), 'msg_dm_content_dlq', ['msgkey'], unique=False)
    op.create_index(op.f('ix_msg_dm_content_dlq_resolved'), 'msg_dm_content_dlq', ['resolved'], unique=False)
    op.create_index(op.f('ix_msg_dm_content_dlq_retry_count'), 'msg_dm_content_dlq', ['retry_count'], unique=False)
    op.create_table('msg_dm_index',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_mid', sa.BIGINT(), nullable=False),
    sa.Column('talker_mid', sa.BIGINT(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('msgkey', sa.BIGINT(), nullable=False),
    sa.Column('sender_uid', sa.BIGINT(), nullable=False),
    sa.Column('msg_type', sa.Enum('TEXT', 'IMAGE', 'SYSTEM', name='dmmsgtypeenum'), nullable=False),
    sa.Column('msg_status', sa.Enum('NORMAL', 'RECALLED', 'DELETED', name='dmmsgstatusenum'), nullable=False),
    sa.Column('msg_ts', sa.BIGINT(), nullable=False),
    sa.Column('content_preview', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('content_ready', sa.Boolean(), nullable=False),
    sa.Column('audit_state', sa.Enum('NORMAL', 'AUDITING', 'REJECTED', 'HIDDEN', name='dmauditstateenum'), nullable=False),
    sa.Column('recalled_at', sa.DateTime(), nullable=True),
    sa.Column('recalled_by', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_mid', 'msgkey', name='uq_dm_index_owner_msgkey')
    )
    op.create_index('idx_dm_index_chat', 'msg_dm_index', ['owner_mid', 'talker_mid', 'msgkey'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_audit_state'), 'msg_dm_index', ['audit_state'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_content_ready'), 'msg_dm_index', ['content_ready'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_created_at'), 'msg_dm_index', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_msg_status'), 'msg_dm_index', ['msg_status'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_msg_ts'), 'msg_dm_index', ['msg_ts'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_msgkey'), 'msg_dm_index', ['msgkey'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_owner_mid'), 'msg_dm_index', ['owner_mid'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_session_key'), 'msg_dm_index', ['session_key'], unique=False)
    op.create_table('msg_dm_session',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_mid', sa.BIGINT(), nullable=False),
    sa.Column('talker_mid', sa.BIGINT(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('session_type', sa.Enum('SINGLE', name='dmsessiontypeenum'), nullable=False),
    sa.Column('talker_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('talker_avatar', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('last_msgkey', sa.BIGINT(), nullable=True),
    sa.Column('last_content_preview', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('last_msg_ts', sa.BIGINT(), nullable=False),
    sa.Column('last_sender_uid', sa.BIGINT(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('ack_msgkey', sa.BIGINT(), nullable=True),
    sa.Column('relation', sa.Enum('NORMAL', 'STRANGER', name='dmrelationenum'), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_mid', 'talker_mid', name='uq_dm_session_owner_talker')
    )
    op.create_index('idx_dm_session_list', 'msg_dm_session', ['owner_mid', 'is_deleted', 'last_msg_ts'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_created_at'), 'msg_dm_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_is_deleted'), 'msg_dm_session', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_last_msg_ts'), 'msg_dm_session', ['last_msg_ts'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_owner_mid'), 'msg_dm_session', ['owner_mid'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_relation'), 'msg_dm_session', ['relation'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_session_key'), 'msg_dm_session', ['session_key'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_talker_mid'), 'msg_dm_session', ['talker_mid'], unique=False)
    op.create_table('msg_event',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('event_type', sa.Enum('LIKE', 'REPLY', 'AT', 'AUDIT_REJECT', 'HIDE', 'REPORT_REJECT', 'REPORT_RESOLVED', name='eventtypeenum'), nullable=False),
    sa.Column('source_type', sa.Enum('VIDEO', 'DYNAMIC', 'ARTICLE', 'COMMENT', 'LOTTERY', 'OTHER', name='sourcetypeenum'), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('biz_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('actor_mid', sa.BIGINT(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('push_strategy', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('pushed', sa.Boolean(), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_event_dedup')
    )
    op.create_index('idx_event_group', 'msg_event', ['mid', 'event_type', 'source_type', 'source_id'], unique=False)
    op.create_index('idx_event_timeline', 'msg_event', ['mid', 'event_type', 'id'], unique=False)
    op.create_index(op.f('ix_msg_event_actor_mid'), 'msg_event', ['actor_mid'], unique=False)
    op.create_index(op.f('ix_msg_event_created_at'), 'msg_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_event_is_read'), 'msg_event', ['is_read'], unique=False)
    op.create_index(op.f('ix_msg_event_mid'), 'msg_event', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_event_pushed'), 'msg_event', ['pushed'], unique=False)
    op.create_table('msg_event_cursor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('event_type', sa.Enum('LIKE', 'REPLY', 'AT', 'AUDIT_REJECT', 'HIDE', 'REPORT_REJECT', 'REPORT_RESOLVED', name='eventtypeenum'), nullable=False),
    sa.Column('last_read_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', 'event_type', name='uq_event_cursor_mid_type')
    )
    op.create_index(op.f('ix_msg_event_cursor_created_at'), 'msg_event_cursor', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_event_cursor_mid'), 'msg_event_cursor', ['mid'], unique=False)
    op.create_table('msg_notify',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('jump_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('target_type', sa.Enum('ALL', 'ROLE', 'LEVEL', 'VIP', 'CUSTOM', name='notifytargettypeenum'), nullable=False),
    sa.Column('target_value', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('level', sa.Enum('NORMAL', 'IMPORTANT', 'URGENT', name='notifylevelenum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'REVOKED', name='notifystatusenum'), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('creator_mid', sa.BIGINT(), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msg_notify_created_at'), 'msg_notify', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_notify_creator_mid'), 'msg_notify', ['creator_mid'], unique=False)
    op.create_index(op.f('ix_msg_notify_dispatched'), 'msg_notify', ['dispatched'], unique=False)
    op.create_index(op.f('ix_msg_notify_publish_at'), 'msg_notify', ['publish_at'], unique=False)
    op.create_index(op.f('ix_msg_notify_status'), 'msg_notify', ['status'], unique=False)
    op.create_index(op.f('ix_msg_notify_target_type'), 'msg_notify', ['target_type'], unique=False)
    op.create_table('msg_notify_cursor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('last_notify_id', sa.Integer(), nullable=False),
    sa.Column('last_pull_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', name='uq_notify_cursor_mid')
    )
    op.create_index(op.f('ix_msg_notify_cursor_created_at'), 'msg_notify_cursor', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_notify_cursor_mid'), 'msg_notify_cursor', ['mid'], unique=False)
    op.create_table('msg_notify_state',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('notify_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', 'notify_id', name='uq_notify_state_mid_notify')
    )
    op.create_index(op.f('ix_msg_notify_state_created_at'), 'msg_notify_state', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_notify_state_is_read'), 'msg_notify_state', ['is_read'], unique=False)
    op.create_index(op.f('ix_msg_notify_state_mid'), 'msg_notify_state', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_notify_state_notify_id'), 'msg_notify_state', ['notify_id'], unique=False)
    op.create_table('msg_user_activity',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('pending_push_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', name='uq_user_activity_mid')
    )
    op.create_index(op.f('ix_msg_user_activity_created_at'), 'msg_user_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_activity_last_active_at'), 'msg_user_activity', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_msg_user_activity_mid'), 'msg_user_activity', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_user_activity_pending_push_count'), 'msg_user_activity', ['pending_push_count'], unique=False)
    op.create_table('msg_user_ban',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('ban_services', sa.JSON(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('duration_type', sa.Enum('TEMPORARY', 'PERMANENT', name='bandurationtypeenum'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('banned_until', sa.DateTime(), nullable=True),
    sa.Column('operator_mid', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LIFTED', name='banstatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_ban_mid_status', 'msg_user_ban', ['mid', 'status'], unique=False)
    op.create_index('idx_user_ban_status_created', 'msg_user_ban', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_ban_created_at'), 'msg_user_ban', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_ban_mid'), 'msg_user_ban', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_user_ban_status'), 'msg_user_ban', ['status'], unique=False)
    op.create_table('msg_user_follow',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('target_mid', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('FOLLOWING', 'BLOCKED', name='followstatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', 'target_mid', name='uq_user_follow_mid_target')
    )
    op.create_index('idx_follow_mid_status', 'msg_user_follow', ['mid', 'status', 'created_at'], unique=False)
    op.create_index('idx_follow_target_status', 'msg_user_follow', ['target_mid', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_follow_created_at'), 'msg_user_follow', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_follow_mid'), 'msg_user_follow', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_user_follow_status'), 'msg_user_follow', ['status'], unique=False)
    op.create_index(op.f('ix_msg_user_follow_target_mid'), 'msg_user_follow', ['target_mid'], unique=False)
    op.create_table('msg_user_setting',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('recv_like', sa.Boolean(), nullable=False),
    sa.Column('recv_reply', sa.Boolean(), nullable=False),
    sa.Column('recv_at', sa.Boolean(), nullable=False),
    sa.Column('recv_stranger_dm', sa.Boolean(), nullable=False),
    sa.Column('recv_notify', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('dnd_start_hour', sa.Integer(), nullable=True),
    sa.Column('dnd_end_hour', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', name='uq_user_setting_mid')
    )
    op.create_index(op.f('ix_msg_user_setting_created_at'), 'msg_user_setting', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_setting_mid'), 'msg_user_setting', ['mid'], unique=False)
    op.create_table('TMomentAuditLog',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dynId', sa.BIGINT(), nullable=False),
    sa.Column('operatorMid', sa.BIGINT(), nullable=False),
    sa.Column('operatorRole', sa.Enum('AUTHOR', 'ADMIN', name='momentauditlogoperatorroleenum'), nullable=False),
    sa.Column('fromStatus', sa.Enum('AUDITING', 'NORMAL', 'REJECTED', 'HIDDEN', name='momentauditstatusenum'), nullable=True),
    sa.Column('toStatus', sa.Enum('AUDITING', 'NORMAL', 'REJECTED', 'HIDDEN', name='momentauditstatusenum'), nullable=False),
    sa.Column('actionType', sa.Enum('CREATE', 'EDIT', 'APPROVE', 'REJECT', 'RESUBMIT', 'DELETE', name='momentauditlogactionenum'), nullable=False),
    sa.Column('rejectReason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('clientIp', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('userAgent', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.ForeignKeyConstraint(['dynId'], ['TMoment.dynId'], name='TMomentAuditLog_dynId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk', name='TMomentAuditLog_pkey'),
    comment='动态审核记录：发布/编辑/通过/驳回等流转流水'
    )
    op.create_index('idx_audit_log_action_created', 'TMomentAuditLog', ['actionType', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_log_admin_created', 'TMomentAuditLog', ['operatorMid', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_log_dynid_created', 'TMomentAuditLog', ['dynId', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_TMomentAuditLog_created_at'), 'TMomentAuditLog', ['created_at'], unique=False)
    op.create_table('TMomentDislike',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bizType', sa.Enum('DYNAMIC', 'LOTTERY', 'RPA_ACTION', 'RPA_WORKFLOW', 'RPA_BROWSER', 'RPA_PLUGIN', name='interactionbiztypeenum'), nullable=False),
    sa.Column('bizId', sa.BIGINT(), nullable=False),
    sa.Column('dynId', sa.BIGINT(), nullable=True),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['dynId'], ['TMoment.dynId'], name='TMomentDislike_dynId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk', name='TMomentDislike_pkey'),
    sa.UniqueConstraint('bizType', 'bizId', 'mid', name='TMomentDislike_bizType_bizId_mid_key'),
    comment='点踩明细：一人一踩，唯一约束(bizType,bizId,mid)保证幂等双写'
    )
    op.create_index('idx_dislike_biz', 'TMomentDislike', ['bizType', 'bizId'], unique=False)
    op.create_index('idx_dislike_mid_time', 'TMomentDislike', ['mid', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_TMomentDislike_created_at'), 'TMomentDislike', ['created_at'], unique=False)
    op.create_index(op.f('ix_TMomentDislike_dynId'), 'TMomentDislike', ['dynId'], unique=False)
    op.create_table('TMomentLike',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bizType', sa.Enum('DYNAMIC', 'LOTTERY', 'RPA_ACTION', 'RPA_WORKFLOW', 'RPA_BROWSER', 'RPA_PLUGIN', name='interactionbiztypeenum'), nullable=False),
    sa.Column('bizId', sa.BIGINT(), nullable=False),
    sa.Column('dynId', sa.BIGINT(), nullable=True),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('likeType', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dynId'], ['TMoment.dynId'], name='TMomentLike_dynId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk', name='TMomentLike_pkey'),
    sa.UniqueConstraint('bizType', 'bizId', 'mid', name='TMomentLike_bizType_bizId_mid_key'),
    comment='点赞明细：一人一赞，唯一约束(bizType,bizId,mid)保证幂等双写'
    )
    op.create_index('idx_like_biz', 'TMomentLike', ['bizType', 'bizId'], unique=False)
    op.create_index('idx_like_mid_time', 'TMomentLike', ['mid', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_TMomentLike_created_at'), 'TMomentLike', ['created_at'], unique=False)
    op.create_index(op.f('ix_TMomentLike_dynId'), 'TMomentLike', ['dynId'], unique=False)
    op.create_table('TMomentTopicRel',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pk', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dynId', sa.BIGINT(), nullable=False),
    sa.Column('topicId', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['dynId'], ['TMoment.dynId'], name='TMomentTopicRel_dynId_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk', name='TMomentTopicRel_pkey'),
    sa.UniqueConstraint('dynId', 'topicId', name='TMomentTopicRel_dynId_topicId_key'),
    comment='动态-话题多对多关系：一条动态多话题（上限5），TMoment.topicId=主话题'
    )
    op.create_index('idx_topic_rel_topic', 'TMomentTopicRel', ['topicId', 'dynId'], unique=False)
    op.create_index(op.f('ix_TMomentTopicRel_created_at'), 'TMomentTopicRel', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TMomentTopicRel_created_at'), table_name='TMomentTopicRel')
    op.drop_index('idx_topic_rel_topic', table_name='TMomentTopicRel')
    op.drop_table('TMomentTopicRel')
    op.drop_index(op.f('ix_TMomentLike_dynId'), table_name='TMomentLike')
    op.drop_index(op.f('ix_TMomentLike_created_at'), table_name='TMomentLike')
    op.drop_index('idx_like_mid_time', table_name='TMomentLike')
    op.drop_index('idx_like_biz', table_name='TMomentLike')
    op.drop_table('TMomentLike')
    op.drop_index(op.f('ix_TMomentDislike_dynId'), table_name='TMomentDislike')
    op.drop_index(op.f('ix_TMomentDislike_created_at'), table_name='TMomentDislike')
    op.drop_index('idx_dislike_mid_time', table_name='TMomentDislike')
    op.drop_index('idx_dislike_biz', table_name='TMomentDislike')
    op.drop_table('TMomentDislike')
    op.drop_index(op.f('ix_TMomentAuditLog_created_at'), table_name='TMomentAuditLog')
    op.drop_index('idx_audit_log_dynid_created', table_name='TMomentAuditLog')
    op.drop_index('idx_audit_log_admin_created', table_name='TMomentAuditLog')
    op.drop_index('idx_audit_log_action_created', table_name='TMomentAuditLog')
    op.drop_table('TMomentAuditLog')
    op.drop_index(op.f('ix_msg_user_setting_mid'), table_name='msg_user_setting')
    op.drop_index(op.f('ix_msg_user_setting_created_at'), table_name='msg_user_setting')
    op.drop_table('msg_user_setting')
    op.drop_index(op.f('ix_msg_user_follow_target_mid'), table_name='msg_user_follow')
    op.drop_index(op.f('ix_msg_user_follow_status'), table_name='msg_user_follow')
    op.drop_index(op.f('ix_msg_user_follow_mid'), table_name='msg_user_follow')
    op.drop_index(op.f('ix_msg_user_follow_created_at'), table_name='msg_user_follow')
    op.drop_index('idx_follow_target_status', table_name='msg_user_follow')
    op.drop_index('idx_follow_mid_status', table_name='msg_user_follow')
    op.drop_table('msg_user_follow')
    op.drop_index(op.f('ix_msg_user_ban_status'), table_name='msg_user_ban')
    op.drop_index(op.f('ix_msg_user_ban_mid'), table_name='msg_user_ban')
    op.drop_index(op.f('ix_msg_user_ban_created_at'), table_name='msg_user_ban')
    op.drop_index('idx_user_ban_status_created', table_name='msg_user_ban')
    op.drop_index('idx_user_ban_mid_status', table_name='msg_user_ban')
    op.drop_table('msg_user_ban')
    op.drop_index(op.f('ix_msg_user_activity_pending_push_count'), table_name='msg_user_activity')
    op.drop_index(op.f('ix_msg_user_activity_mid'), table_name='msg_user_activity')
    op.drop_index(op.f('ix_msg_user_activity_last_active_at'), table_name='msg_user_activity')
    op.drop_index(op.f('ix_msg_user_activity_created_at'), table_name='msg_user_activity')
    op.drop_table('msg_user_activity')
    op.drop_index(op.f('ix_msg_notify_state_notify_id'), table_name='msg_notify_state')
    op.drop_index(op.f('ix_msg_notify_state_mid'), table_name='msg_notify_state')
    op.drop_index(op.f('ix_msg_notify_state_is_read'), table_name='msg_notify_state')
    op.drop_index(op.f('ix_msg_notify_state_created_at'), table_name='msg_notify_state')
    op.drop_table('msg_notify_state')
    op.drop_index(op.f('ix_msg_notify_cursor_mid'), table_name='msg_notify_cursor')
    op.drop_index(op.f('ix_msg_notify_cursor_created_at'), table_name='msg_notify_cursor')
    op.drop_table('msg_notify_cursor')
    op.drop_index(op.f('ix_msg_notify_target_type'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_status'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_publish_at'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_dispatched'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_creator_mid'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_created_at'), table_name='msg_notify')
    op.drop_table('msg_notify')
    op.drop_index(op.f('ix_msg_event_cursor_mid'), table_name='msg_event_cursor')
    op.drop_index(op.f('ix_msg_event_cursor_created_at'), table_name='msg_event_cursor')
    op.drop_table('msg_event_cursor')
    op.drop_index(op.f('ix_msg_event_pushed'), table_name='msg_event')
    op.drop_index(op.f('ix_msg_event_mid'), table_name='msg_event')
    op.drop_index(op.f('ix_msg_event_is_read'), table_name='msg_event')
    op.drop_index(op.f('ix_msg_event_created_at'), table_name='msg_event')
    op.drop_index(op.f('ix_msg_event_actor_mid'), table_name='msg_event')
    op.drop_index('idx_event_timeline', table_name='msg_event')
    op.drop_index('idx_event_group', table_name='msg_event')
    op.drop_table('msg_event')
    op.drop_index(op.f('ix_msg_dm_session_talker_mid'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_session_key'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_relation'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_owner_mid'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_last_msg_ts'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_is_deleted'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_created_at'), table_name='msg_dm_session')
    op.drop_index('idx_dm_session_list', table_name='msg_dm_session')
    op.drop_table('msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_index_session_key'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_owner_mid'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_msgkey'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_msg_ts'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_msg_status'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_created_at'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_content_ready'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_audit_state'), table_name='msg_dm_index')
    op.drop_index('idx_dm_index_chat', table_name='msg_dm_index')
    op.drop_table('msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_content_dlq_retry_count'), table_name='msg_dm_content_dlq')
    op.drop_index(op.f('ix_msg_dm_content_dlq_resolved'), table_name='msg_dm_content_dlq')
    op.drop_index(op.f('ix_msg_dm_content_dlq_msgkey'), table_name='msg_dm_content_dlq')
    op.drop_index(op.f('ix_msg_dm_content_dlq_created_at'), table_name='msg_dm_content_dlq')
    op.drop_table('msg_dm_content_dlq')
    op.drop_index(op.f('ix_msg_comment_subject_up_mid'), table_name='msg_comment_subject')
    op.drop_index(op.f('ix_msg_comment_subject_state'), table_name='msg_comment_subject')
    op.drop_index(op.f('ix_msg_comment_subject_oid'), table_name='msg_comment_subject')
    op.drop_index(op.f('ix_msg_comment_subject_created_at'), table_name='msg_comment_subject')
    op.drop_table('msg_comment_subject')
    op.drop_index(op.f('ix_msg_comment_report_resourceType'), table_name='msg_comment_report')
    op.drop_index(op.f('ix_msg_comment_report_reportMid'), table_name='msg_comment_report')
    op.drop_index(op.f('ix_msg_comment_report_bizType'), table_name='msg_comment_report')
    op.drop_index(op.f('ix_msg_comment_report_bizId'), table_name='msg_comment_report')
    op.drop_index('idx_comment_report_biz', table_name='msg_comment_report')
    op.drop_table('msg_comment_report')
    op.drop_index(op.f('ix_msg_comment_index_state'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_root'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_oid'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_mid'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_hot_score'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_dialog'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_created_at'), table_name='msg_comment_index')
    op.drop_index('idx_comment_user', table_name='msg_comment_index')
    op.drop_index('idx_comment_time', table_name='msg_comment_index')
    op.drop_index('idx_comment_sub', table_name='msg_comment_index')
    op.drop_index('idx_comment_hot', table_name='msg_comment_index')
    op.drop_table('msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_content_created_at'), table_name='msg_comment_content')
    op.drop_table('msg_comment_content')
    op.drop_index(op.f('ix_msg_comment_at_rpid'), table_name='msg_comment_at')
    op.drop_index(op.f('ix_msg_comment_at_created_at'), table_name='msg_comment_at')
    op.drop_index(op.f('ix_msg_comment_at_at_mid'), table_name='msg_comment_at')
    op.drop_index('idx_comment_at_pending', table_name='msg_comment_at')
    op.drop_table('msg_comment_at')
    op.drop_index(op.f('ix_msg_comment_action_rpid'), table_name='msg_comment_action')
    op.drop_index(op.f('ix_msg_comment_action_mid'), table_name='msg_comment_action')
    op.drop_index(op.f('ix_msg_comment_action_created_at'), table_name='msg_comment_action')
    op.drop_index(op.f('ix_msg_comment_action_action'), table_name='msg_comment_action')
    op.drop_table('msg_comment_action')
    op.drop_index(op.f('ix_msg_admin_mid'), table_name='msg_admin')
    op.drop_index(op.f('ix_msg_admin_created_at'), table_name='msg_admin')
    op.drop_table('msg_admin')
    op.drop_index(op.f('ix_moment_author_quality_created_at'), table_name='moment_author_quality')
    op.drop_table('moment_author_quality')
    op.drop_index(op.f('ix_TUserReport_resourceType'), table_name='TUserReport')
    op.drop_index(op.f('ix_TUserReport_reportMid'), table_name='TUserReport')
    op.drop_index(op.f('ix_TUserReport_bizType'), table_name='TUserReport')
    op.drop_index(op.f('ix_TUserReport_bizId'), table_name='TUserReport')
    op.drop_index('idx_tuser_report_biz', table_name='TUserReport')
    op.drop_table('TUserReport')
    op.drop_index(op.f('ix_TUserFavoriteSetting_created_at'), table_name='TUserFavoriteSetting')
    op.drop_table('TUserFavoriteSetting')
    op.drop_index(op.f('ix_TUserAvatarAudit_created_at'), table_name='TUserAvatarAudit')
    op.drop_index('idx_avatar_audit_status_created', table_name='TUserAvatarAudit')
    op.drop_index('idx_avatar_audit_mid_created', table_name='TUserAvatarAudit')
    op.drop_table('TUserAvatarAudit')
    op.drop_index(op.f('ix_TResourceReport_resourceType'), table_name='TResourceReport')
    op.drop_index(op.f('ix_TResourceReport_reportMid'), table_name='TResourceReport')
    op.drop_index(op.f('ix_TResourceReport_bizType'), table_name='TResourceReport')
    op.drop_index(op.f('ix_TResourceReport_bizId'), table_name='TResourceReport')
    op.drop_index('idx_tresource_report_biz', table_name='TResourceReport')
    op.drop_table('TResourceReport')
    op.drop_index(op.f('ix_TResourceFeed_created_at'), table_name='TResourceFeed')
    op.drop_index('idx_resfeed_status_pubtime', table_name='TResourceFeed')
    op.drop_index('idx_resfeed_mid_pubtime', table_name='TResourceFeed')
    op.drop_table('TResourceFeed')
    op.drop_index(op.f('ix_TMomentTopic_created_at'), table_name='TMomentTopic')
    op.drop_index('idx_topic_creator_created', table_name='TMomentTopic')
    op.drop_index('idx_topic_audit_created', table_name='TMomentTopic')
    op.drop_table('TMomentTopic')
    op.drop_index(op.f('ix_TMomentFavorite_mid'), table_name='TMomentFavorite')
    op.drop_index(op.f('ix_TMomentFavorite_folderId'), table_name='TMomentFavorite')
    op.drop_index(op.f('ix_TMomentFavorite_dynId'), table_name='TMomentFavorite')
    op.drop_index(op.f('ix_TMomentFavorite_created_at'), table_name='TMomentFavorite')
    op.drop_index('idx_fav_mid_created', table_name='TMomentFavorite')
    op.drop_index('idx_fav_folder_created', table_name='TMomentFavorite')
    op.drop_index('idx_fav_biz', table_name='TMomentFavorite')
    op.drop_table('TMomentFavorite')
    op.drop_index(op.f('ix_TMoment_created_at'), table_name='TMoment')
    op.drop_index('idx_dynamic_topic_pubtime', table_name='TMoment')
    op.drop_index('idx_dynamic_repost_src', table_name='TMoment')
    op.drop_index('idx_dynamic_pubtime_visible', table_name='TMoment')
    op.drop_index('idx_dynamic_mid_pubtime', table_name='TMoment')
    op.drop_index('idx_dynamic_mid_created', table_name='TMoment')
    op.drop_index('idx_dynamic_biz', table_name='TMoment')
    op.drop_index('idx_dynamic_auditing_created', table_name='TMoment')
    op.drop_table('TMoment')
    op.drop_index(op.f('ix_TInteractionViewLog_created_at'), table_name='TInteractionViewLog')
    op.drop_table('TInteractionViewLog')
    op.drop_index(op.f('ix_TInteractionStat_created_at'), table_name='TInteractionStat')
    op.drop_table('TInteractionStat')
    op.drop_index(op.f('ix_TFolderCoverAudit_created_at'), table_name='TFolderCoverAudit')
    op.drop_index('idx_folder_cover_audit_status_created', table_name='TFolderCoverAudit')
    op.drop_index('idx_folder_cover_audit_folder_status', table_name='TFolderCoverAudit')
    op.drop_table('TFolderCoverAudit')
    op.drop_index(op.f('ix_TFavoriteFolder_mid'), table_name='TFavoriteFolder')
    op.drop_index(op.f('ix_TFavoriteFolder_created_at'), table_name='TFavoriteFolder')
    op.drop_index('idx_fav_folder_mid_created', table_name='TFavoriteFolder')
    op.drop_table('TFavoriteFolder')
    # ### end Alembic commands ###
