"""init

Revision ID: 1444c17689f6
Revises: 
Create Date: 2026-08-10 02:57:52.053141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from app.models.db.base import _IntEnumColumn


# revision identifiers, used by Alembic.
revision: str = '1444c17689f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg_admin',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('granted_by', sa.BIGINT(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', name='uq_msg_admin_mid')
    )
    op.create_index(op.f('ix_msg_admin_created_at'), 'msg_admin', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_admin_mid'), 'msg_admin', ['mid'], unique=False)
    op.create_table('msg_comment_action',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpid', sa.BIGINT(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('action', app.models.db.base._IntEnumColumn(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rpid', 'mid', name='uq_comment_action_rpid_mid')
    )
    op.create_index(op.f('ix_msg_comment_action_action'), 'msg_comment_action', ['action'], unique=False)
    op.create_index(op.f('ix_msg_comment_action_created_at'), 'msg_comment_action', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_comment_action_mid'), 'msg_comment_action', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_comment_action_rpid'), 'msg_comment_action', ['rpid'], unique=False)
    op.create_table('msg_comment_at',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpid', sa.BIGINT(), nullable=False),
    sa.Column('oid', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('dynamic', 'article', 'lottery', 'feedback', 'other', name='commenttypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('from_mid', sa.BIGINT(), nullable=False),
    sa.Column('at_mid', sa.BIGINT(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rpid', 'at_mid', name='uq_comment_at_rpid_at_mid')
    )
    op.create_index('idx_comment_at_pending', 'msg_comment_at', ['notified', 'id'], unique=False)
    op.create_index(op.f('ix_msg_comment_at_at_mid'), 'msg_comment_at', ['at_mid'], unique=False)
    op.create_index(op.f('ix_msg_comment_at_created_at'), 'msg_comment_at', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_comment_at_rpid'), 'msg_comment_at', ['rpid'], unique=False)
    op.create_table('msg_comment_content',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rpid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('pictures', sa.JSON(), nullable=False),
    sa.Column('at_mids', sa.JSON(), nullable=False),
    sa.Column('emote_meta', sa.JSON(), nullable=True),
    sa.Column('ip_v4', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('ip_v6', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('plat', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.PrimaryKeyConstraint('rpid')
    )
    op.create_index(op.f('ix_msg_comment_content_created_at'), 'msg_comment_content', ['created_at'], unique=False)
    op.create_table('msg_comment_index',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('rpid', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('oid', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('dynamic', 'article', 'lottery', 'feedback', 'other', name='commenttypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('root', sa.BIGINT(), nullable=False),
    sa.Column('parent', sa.BIGINT(), nullable=False),
    sa.Column('dialog', sa.BIGINT(), nullable=False),
    sa.Column('reply_to_mid', sa.BIGINT(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('hate_count', sa.Integer(), nullable=False),
    sa.Column('rcount', sa.Integer(), nullable=False),
    sa.Column('hot_score', sa.Float(), nullable=False),
    sa.Column('state', sa.Enum('normal', 'auditing', 'rejected', 'hidden', 'deleted', name='commentstateenum', native_enum=False, length=16), nullable=False),
    sa.Column('attr', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rpid')
    )
    op.create_index('idx_comment_hot', 'msg_comment_index', ['oid', 'type', 'root', 'state', 'hot_score', 'rpid'], unique=False)
    op.create_index('idx_comment_sub', 'msg_comment_index', ['root', 'state', 'rpid'], unique=False)
    op.create_index('idx_comment_time', 'msg_comment_index', ['oid', 'type', 'root', 'state', 'rpid'], unique=False)
    op.create_index('idx_comment_user', 'msg_comment_index', ['mid', 'rpid'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_created_at'), 'msg_comment_index', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_dialog'), 'msg_comment_index', ['dialog'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_hot_score'), 'msg_comment_index', ['hot_score'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_mid'), 'msg_comment_index', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_oid'), 'msg_comment_index', ['oid'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_root'), 'msg_comment_index', ['root'], unique=False)
    op.create_index(op.f('ix_msg_comment_index_state'), 'msg_comment_index', ['state'], unique=False)
    op.create_table('msg_comment_subject',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oid', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('dynamic', 'article', 'lottery', 'feedback', 'other', name='commenttypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('up_mid', sa.BIGINT(), nullable=False),
    sa.Column('root_count', sa.Integer(), nullable=False),
    sa.Column('all_count', sa.Integer(), nullable=False),
    sa.Column('floor_seq', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('normal', 'closed', name='commentsubjectstateenum', native_enum=False, length=16), nullable=False),
    sa.Column('top_rpid', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oid', 'type', name='uq_comment_subject_oid_type')
    )
    op.create_index(op.f('ix_msg_comment_subject_created_at'), 'msg_comment_subject', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_comment_subject_oid'), 'msg_comment_subject', ['oid'], unique=False)
    op.create_index(op.f('ix_msg_comment_subject_state'), 'msg_comment_subject', ['state'], unique=False)
    op.create_index(op.f('ix_msg_comment_subject_up_mid'), 'msg_comment_subject', ['up_mid'], unique=False)
    op.create_table('msg_dm_content_dlq',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msgkey', sa.BIGINT(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('sender_uid', sa.BIGINT(), nullable=False),
    sa.Column('receiver_uid', sa.BIGINT(), nullable=False),
    sa.Column('msg_type', sa.Enum('text', 'image', 'system', name='dmmsgtypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('msg_ts', sa.BIGINT(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msgkey', name='uq_dm_dlq_msgkey')
    )
    op.create_index(op.f('ix_msg_dm_content_dlq_created_at'), 'msg_dm_content_dlq', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_dm_content_dlq_msgkey'), 'msg_dm_content_dlq', ['msgkey'], unique=False)
    op.create_index(op.f('ix_msg_dm_content_dlq_resolved'), 'msg_dm_content_dlq', ['resolved'], unique=False)
    op.create_index(op.f('ix_msg_dm_content_dlq_retry_count'), 'msg_dm_content_dlq', ['retry_count'], unique=False)
    op.create_table('msg_dm_index',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_mid', sa.BIGINT(), nullable=False),
    sa.Column('talker_mid', sa.BIGINT(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('msgkey', sa.BIGINT(), nullable=False),
    sa.Column('sender_uid', sa.BIGINT(), nullable=False),
    sa.Column('msg_type', sa.Enum('text', 'image', 'system', name='dmmsgtypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('msg_status', app.models.db.base._IntEnumColumn(), nullable=False),
    sa.Column('msg_ts', sa.BIGINT(), nullable=False),
    sa.Column('content_preview', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('content_ready', sa.Boolean(), nullable=False),
    sa.Column('audit_state', sa.Enum('normal', 'auditing', 'rejected', 'hidden', name='dmauditstateenum', native_enum=False, length=16), nullable=False),
    sa.Column('recalled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_mid', 'msgkey', name='uq_dm_index_owner_msgkey')
    )
    op.create_index('idx_dm_index_chat', 'msg_dm_index', ['owner_mid', 'talker_mid', 'msgkey'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_audit_state'), 'msg_dm_index', ['audit_state'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_content_ready'), 'msg_dm_index', ['content_ready'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_created_at'), 'msg_dm_index', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_msg_status'), 'msg_dm_index', ['msg_status'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_msg_ts'), 'msg_dm_index', ['msg_ts'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_msgkey'), 'msg_dm_index', ['msgkey'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_owner_mid'), 'msg_dm_index', ['owner_mid'], unique=False)
    op.create_index(op.f('ix_msg_dm_index_session_key'), 'msg_dm_index', ['session_key'], unique=False)
    op.create_table('msg_dm_session',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_mid', sa.BIGINT(), nullable=False),
    sa.Column('talker_mid', sa.BIGINT(), nullable=False),
    sa.Column('session_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('session_type', app.models.db.base._IntEnumColumn(), nullable=False),
    sa.Column('talker_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('talker_avatar', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('last_msgkey', sa.BIGINT(), nullable=True),
    sa.Column('last_content_preview', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('last_msg_ts', sa.BIGINT(), nullable=False),
    sa.Column('last_sender_uid', sa.BIGINT(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('ack_msgkey', sa.BIGINT(), nullable=True),
    sa.Column('relation', sa.Enum('normal', 'stranger', name='dmrelationenum', native_enum=False, length=16), nullable=False),
    sa.Column('is_top', sa.Boolean(), nullable=False),
    sa.Column('is_muted', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_mid', 'talker_mid', name='uq_dm_session_owner_talker')
    )
    op.create_index('idx_dm_session_list', 'msg_dm_session', ['owner_mid', 'is_deleted', 'last_msg_ts'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_created_at'), 'msg_dm_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_is_deleted'), 'msg_dm_session', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_last_msg_ts'), 'msg_dm_session', ['last_msg_ts'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_owner_mid'), 'msg_dm_session', ['owner_mid'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_relation'), 'msg_dm_session', ['relation'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_session_key'), 'msg_dm_session', ['session_key'], unique=False)
    op.create_index(op.f('ix_msg_dm_session_talker_mid'), 'msg_dm_session', ['talker_mid'], unique=False)
    op.create_table('msg_event',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('event_type', sa.Enum('like', 'reply', 'at', name='eventtypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('source_type', sa.Enum('video', 'dynamic', 'article', 'comment', 'lottery', 'other', name='sourcetypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('source_title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('source_cover', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('actor_mid', sa.BIGINT(), nullable=False),
    sa.Column('actor_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('actor_avatar', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('jump_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('push_strategy', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('pushed', sa.Boolean(), nullable=False),
    sa.Column('dedup_key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_event_dedup')
    )
    op.create_index('idx_event_group', 'msg_event', ['mid', 'event_type', 'source_type', 'source_id'], unique=False)
    op.create_index('idx_event_timeline', 'msg_event', ['mid', 'event_type', 'id'], unique=False)
    op.create_index(op.f('ix_msg_event_actor_mid'), 'msg_event', ['actor_mid'], unique=False)
    op.create_index(op.f('ix_msg_event_created_at'), 'msg_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_event_is_read'), 'msg_event', ['is_read'], unique=False)
    op.create_index(op.f('ix_msg_event_mid'), 'msg_event', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_event_pushed'), 'msg_event', ['pushed'], unique=False)
    op.create_table('msg_event_cursor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('event_type', sa.Enum('like', 'reply', 'at', name='eventtypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('last_read_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', 'event_type', name='uq_event_cursor_mid_type')
    )
    op.create_index(op.f('ix_msg_event_cursor_created_at'), 'msg_event_cursor', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_event_cursor_mid'), 'msg_event_cursor', ['mid'], unique=False)
    op.create_table('msg_notify',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('jump_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('target_type', sa.Enum('all', 'role', 'level', 'vip', 'custom', name='notifytargettypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('target_value', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('level', sa.Enum('normal', 'important', 'urgent', name='notifylevelenum', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'revoked', name='notifystatusenum', native_enum=False, length=16), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.Column('creator_mid', sa.BIGINT(), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msg_notify_created_at'), 'msg_notify', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_notify_creator_mid'), 'msg_notify', ['creator_mid'], unique=False)
    op.create_index(op.f('ix_msg_notify_dispatched'), 'msg_notify', ['dispatched'], unique=False)
    op.create_index(op.f('ix_msg_notify_publish_at'), 'msg_notify', ['publish_at'], unique=False)
    op.create_index(op.f('ix_msg_notify_status'), 'msg_notify', ['status'], unique=False)
    op.create_index(op.f('ix_msg_notify_target_type'), 'msg_notify', ['target_type'], unique=False)
    op.create_table('msg_notify_cursor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('last_notify_id', sa.Integer(), nullable=False),
    sa.Column('last_pull_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', name='uq_notify_cursor_mid')
    )
    op.create_index(op.f('ix_msg_notify_cursor_created_at'), 'msg_notify_cursor', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_notify_cursor_mid'), 'msg_notify_cursor', ['mid'], unique=False)
    op.create_table('msg_notify_state',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('notify_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', 'notify_id', name='uq_notify_state_mid_notify')
    )
    op.create_index(op.f('ix_msg_notify_state_created_at'), 'msg_notify_state', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_notify_state_is_read'), 'msg_notify_state', ['is_read'], unique=False)
    op.create_index(op.f('ix_msg_notify_state_mid'), 'msg_notify_state', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_notify_state_notify_id'), 'msg_notify_state', ['notify_id'], unique=False)
    op.create_table('msg_user_activity',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('pending_push_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', name='uq_user_activity_mid')
    )
    op.create_index(op.f('ix_msg_user_activity_created_at'), 'msg_user_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_activity_last_active_at'), 'msg_user_activity', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_msg_user_activity_mid'), 'msg_user_activity', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_user_activity_pending_push_count'), 'msg_user_activity', ['pending_push_count'], unique=False)
    op.create_table('msg_user_ban',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('ban_services', sa.JSON(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('duration_type', sa.Enum('temporary', 'permanent', name='bandurationtypeenum', native_enum=False, length=16), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('banned_until', sa.DateTime(), nullable=True),
    sa.Column('operator_mid', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('active', 'lifted', name='banstatusenum', native_enum=False, length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_ban_mid_status', 'msg_user_ban', ['mid', 'status'], unique=False)
    op.create_index('idx_user_ban_status_created', 'msg_user_ban', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_ban_created_at'), 'msg_user_ban', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_ban_mid'), 'msg_user_ban', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_user_ban_status'), 'msg_user_ban', ['status'], unique=False)
    op.create_table('msg_user_follow',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('target_mid', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('following', 'blocked', name='followstatusenum', native_enum=False, length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', 'target_mid', name='uq_user_follow_mid_target')
    )
    op.create_index('idx_follow_mid_status', 'msg_user_follow', ['mid', 'status', 'created_at'], unique=False)
    op.create_index('idx_follow_target_status', 'msg_user_follow', ['target_mid', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_follow_created_at'), 'msg_user_follow', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_follow_mid'), 'msg_user_follow', ['mid'], unique=False)
    op.create_index(op.f('ix_msg_user_follow_status'), 'msg_user_follow', ['status'], unique=False)
    op.create_index(op.f('ix_msg_user_follow_target_mid'), 'msg_user_follow', ['target_mid'], unique=False)
    op.create_table('msg_user_setting',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mid', sa.BIGINT(), nullable=False),
    sa.Column('recv_like', sa.Boolean(), nullable=False),
    sa.Column('recv_reply', sa.Boolean(), nullable=False),
    sa.Column('recv_at', sa.Boolean(), nullable=False),
    sa.Column('recv_stranger_dm', sa.Boolean(), nullable=False),
    sa.Column('recv_notify', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('dnd_start_hour', sa.Integer(), nullable=True),
    sa.Column('dnd_end_hour', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mid', name='uq_user_setting_mid')
    )
    op.create_index(op.f('ix_msg_user_setting_created_at'), 'msg_user_setting', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_user_setting_mid'), 'msg_user_setting', ['mid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_msg_user_setting_mid'), table_name='msg_user_setting')
    op.drop_index(op.f('ix_msg_user_setting_created_at'), table_name='msg_user_setting')
    op.drop_table('msg_user_setting')
    op.drop_index(op.f('ix_msg_user_follow_target_mid'), table_name='msg_user_follow')
    op.drop_index(op.f('ix_msg_user_follow_status'), table_name='msg_user_follow')
    op.drop_index(op.f('ix_msg_user_follow_mid'), table_name='msg_user_follow')
    op.drop_index(op.f('ix_msg_user_follow_created_at'), table_name='msg_user_follow')
    op.drop_index('idx_follow_target_status', table_name='msg_user_follow')
    op.drop_index('idx_follow_mid_status', table_name='msg_user_follow')
    op.drop_table('msg_user_follow')
    op.drop_index(op.f('ix_msg_user_ban_status'), table_name='msg_user_ban')
    op.drop_index(op.f('ix_msg_user_ban_mid'), table_name='msg_user_ban')
    op.drop_index(op.f('ix_msg_user_ban_created_at'), table_name='msg_user_ban')
    op.drop_index('idx_user_ban_status_created', table_name='msg_user_ban')
    op.drop_index('idx_user_ban_mid_status', table_name='msg_user_ban')
    op.drop_table('msg_user_ban')
    op.drop_index(op.f('ix_msg_user_activity_pending_push_count'), table_name='msg_user_activity')
    op.drop_index(op.f('ix_msg_user_activity_mid'), table_name='msg_user_activity')
    op.drop_index(op.f('ix_msg_user_activity_last_active_at'), table_name='msg_user_activity')
    op.drop_index(op.f('ix_msg_user_activity_created_at'), table_name='msg_user_activity')
    op.drop_table('msg_user_activity')
    op.drop_index(op.f('ix_msg_notify_state_notify_id'), table_name='msg_notify_state')
    op.drop_index(op.f('ix_msg_notify_state_mid'), table_name='msg_notify_state')
    op.drop_index(op.f('ix_msg_notify_state_is_read'), table_name='msg_notify_state')
    op.drop_index(op.f('ix_msg_notify_state_created_at'), table_name='msg_notify_state')
    op.drop_table('msg_notify_state')
    op.drop_index(op.f('ix_msg_notify_cursor_mid'), table_name='msg_notify_cursor')
    op.drop_index(op.f('ix_msg_notify_cursor_created_at'), table_name='msg_notify_cursor')
    op.drop_table('msg_notify_cursor')
    op.drop_index(op.f('ix_msg_notify_target_type'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_status'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_publish_at'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_dispatched'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_creator_mid'), table_name='msg_notify')
    op.drop_index(op.f('ix_msg_notify_created_at'), table_name='msg_notify')
    op.drop_table('msg_notify')
    op.drop_index(op.f('ix_msg_event_cursor_mid'), table_name='msg_event_cursor')
    op.drop_index(op.f('ix_msg_event_cursor_created_at'), table_name='msg_event_cursor')
    op.drop_table('msg_event_cursor')
    op.drop_index(op.f('ix_msg_event_pushed'), table_name='msg_event')
    op.drop_index(op.f('ix_msg_event_mid'), table_name='msg_event')
    op.drop_index(op.f('ix_msg_event_is_read'), table_name='msg_event')
    op.drop_index(op.f('ix_msg_event_created_at'), table_name='msg_event')
    op.drop_index(op.f('ix_msg_event_actor_mid'), table_name='msg_event')
    op.drop_index('idx_event_timeline', table_name='msg_event')
    op.drop_index('idx_event_group', table_name='msg_event')
    op.drop_table('msg_event')
    op.drop_index(op.f('ix_msg_dm_session_talker_mid'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_session_key'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_relation'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_owner_mid'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_last_msg_ts'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_is_deleted'), table_name='msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_session_created_at'), table_name='msg_dm_session')
    op.drop_index('idx_dm_session_list', table_name='msg_dm_session')
    op.drop_table('msg_dm_session')
    op.drop_index(op.f('ix_msg_dm_index_session_key'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_owner_mid'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_msgkey'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_msg_ts'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_msg_status'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_created_at'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_content_ready'), table_name='msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_index_audit_state'), table_name='msg_dm_index')
    op.drop_index('idx_dm_index_chat', table_name='msg_dm_index')
    op.drop_table('msg_dm_index')
    op.drop_index(op.f('ix_msg_dm_content_dlq_retry_count'), table_name='msg_dm_content_dlq')
    op.drop_index(op.f('ix_msg_dm_content_dlq_resolved'), table_name='msg_dm_content_dlq')
    op.drop_index(op.f('ix_msg_dm_content_dlq_msgkey'), table_name='msg_dm_content_dlq')
    op.drop_index(op.f('ix_msg_dm_content_dlq_created_at'), table_name='msg_dm_content_dlq')
    op.drop_table('msg_dm_content_dlq')
    op.drop_index(op.f('ix_msg_comment_subject_up_mid'), table_name='msg_comment_subject')
    op.drop_index(op.f('ix_msg_comment_subject_state'), table_name='msg_comment_subject')
    op.drop_index(op.f('ix_msg_comment_subject_oid'), table_name='msg_comment_subject')
    op.drop_index(op.f('ix_msg_comment_subject_created_at'), table_name='msg_comment_subject')
    op.drop_table('msg_comment_subject')
    op.drop_index(op.f('ix_msg_comment_index_state'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_root'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_oid'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_mid'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_hot_score'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_dialog'), table_name='msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_index_created_at'), table_name='msg_comment_index')
    op.drop_index('idx_comment_user', table_name='msg_comment_index')
    op.drop_index('idx_comment_time', table_name='msg_comment_index')
    op.drop_index('idx_comment_sub', table_name='msg_comment_index')
    op.drop_index('idx_comment_hot', table_name='msg_comment_index')
    op.drop_table('msg_comment_index')
    op.drop_index(op.f('ix_msg_comment_content_created_at'), table_name='msg_comment_content')
    op.drop_table('msg_comment_content')
    op.drop_index(op.f('ix_msg_comment_at_rpid'), table_name='msg_comment_at')
    op.drop_index(op.f('ix_msg_comment_at_created_at'), table_name='msg_comment_at')
    op.drop_index(op.f('ix_msg_comment_at_at_mid'), table_name='msg_comment_at')
    op.drop_index('idx_comment_at_pending', table_name='msg_comment_at')
    op.drop_table('msg_comment_at')
    op.drop_index(op.f('ix_msg_comment_action_rpid'), table_name='msg_comment_action')
    op.drop_index(op.f('ix_msg_comment_action_mid'), table_name='msg_comment_action')
    op.drop_index(op.f('ix_msg_comment_action_created_at'), table_name='msg_comment_action')
    op.drop_index(op.f('ix_msg_comment_action_action'), table_name='msg_comment_action')
    op.drop_table('msg_comment_action')
    op.drop_index(op.f('ix_msg_admin_mid'), table_name='msg_admin')
    op.drop_index(op.f('ix_msg_admin_created_at'), table_name='msg_admin')
    op.drop_table('msg_admin')
    # ### end Alembic commands ###
