"""baseline from production

Revision ID: 5ccc64b8ab8a
Revises: 
Create Date: 2026-08-08 21:07:33.551146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ccc64b8ab8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SequelizeMeta',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name', name='SequelizeMeta_pkey')
    )
    op.alter_column('TAccountBiliWhisperMsg', 'msg_key',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAccountDetailInfo', 'account_detail_info_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAccountInfo', 'account_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='账户id，自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'TAccountInfo',
        '账户id，自增主键',
        existing_comment=None,
        schema=None
    )
    op.alter_column('TAccountInfo_DashBoardInfo', 'dashboard_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAccountInfo_DashBoardInfo', 'vip',
               existing_type=sa.VARCHAR(length=30),
               comment='vip等级（普通用户，月度大会员，年度大会员，十年大会员，百年大会员）',
               existing_comment='vip等级（普通用户，月度大会员，年度大会员，十年大会员，百年大会员',
               existing_nullable=True)
    op.alter_column('TAccountInfo_LotteryLog', 'account_info_lotteryLog_id',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAccountInfo_ReserveLog', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAtariInfo', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TBiliLotteryInfoRecord', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.add_column('TBiliUserDetail', sa.Column('vip', sa.JSON(), nullable=True))
    op.drop_column('TBiliUserDetail', ' vip')
    op.alter_column('TCommentInteractRelation', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TCommonLog', 'pk',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TDynamicInfo', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TLiveLotteryLog', 'pk',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TLogBiliDailyTask', 'pk',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TLogBiliDailyTask', 'sanlian_ts',
               existing_type=sa.INTEGER(),
               comment='上一次三连任务的时间戳（秒）',
               existing_comment='上一次三连任务的时间戳（秒',
               existing_nullable=True)
    op.alter_column('TLogBiliDailyTask', 'bcoin_ts',
               existing_type=sa.INTEGER(),
               comment='上一次领取b币的时间戳（秒）',
               existing_comment='上一次领取b币的时间戳（秒',
               existing_nullable=True)
    op.alter_column('TLogBiliDailyTask', 'charge_ts',
               existing_type=sa.INTEGER(),
               comment='上一次充电任务的时间戳（秒）',
               existing_comment='上一次充电任务的时间戳（秒',
               existing_nullable=True)
    op.alter_column('TLogBiliDailyTask', 'live_send_gift_ts',
               existing_type=sa.INTEGER(),
               comment='上一次直播间送免费礼物的时间戳（秒）',
               existing_comment='上一次直播间送免费礼物的时间戳（秒',
               existing_nullable=True)
    op.alter_column('TLotteryLogInfo', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TReserveLotteryInfo', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TUserActInfoLog', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('TUserInfo', 'uid',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('ip_info_id_fkey'), 'TUserInfo', type_='foreignkey')
    op.alter_column('TUserNameRecord', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('TUserPwdRecord', 'pk',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TUserPwdRecord', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False)
    op.alter_column('TUserNameRecord', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False)
    op.create_foreign_key(op.f('ip_info_id_fkey'), 'TUserInfo', 'TUserActInfoLog', ['reg_ip_info_id'], ['pk'])
    op.alter_column('TUserInfo', 'uid',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TUserActInfoLog', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False)
    op.alter_column('TReserveLotteryInfo', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TLotteryLogInfo', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TLogBiliDailyTask', 'live_send_gift_ts',
               existing_type=sa.INTEGER(),
               comment='上一次直播间送免费礼物的时间戳（秒',
               existing_comment='上一次直播间送免费礼物的时间戳（秒）',
               existing_nullable=True)
    op.alter_column('TLogBiliDailyTask', 'charge_ts',
               existing_type=sa.INTEGER(),
               comment='上一次充电任务的时间戳（秒',
               existing_comment='上一次充电任务的时间戳（秒）',
               existing_nullable=True)
    op.alter_column('TLogBiliDailyTask', 'bcoin_ts',
               existing_type=sa.INTEGER(),
               comment='上一次领取b币的时间戳（秒',
               existing_comment='上一次领取b币的时间戳（秒）',
               existing_nullable=True)
    op.alter_column('TLogBiliDailyTask', 'sanlian_ts',
               existing_type=sa.INTEGER(),
               comment='上一次三连任务的时间戳（秒',
               existing_comment='上一次三连任务的时间戳（秒）',
               existing_nullable=True)
    op.alter_column('TLogBiliDailyTask', 'pk',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TLiveLotteryLog', 'pk',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TDynamicInfo', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TCommonLog', 'pk',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TCommentInteractRelation', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('TBiliUserDetail', sa.Column(' vip', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('TBiliUserDetail', 'vip')
    op.alter_column('TBiliLotteryInfoRecord', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False)
    op.alter_column('TAtariInfo', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAccountInfo_ReserveLog', 'pk',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAccountInfo_LotteryLog', 'account_info_lotteryLog_id',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAccountInfo_DashBoardInfo', 'vip',
               existing_type=sa.VARCHAR(length=30),
               comment='vip等级（普通用户，月度大会员，年度大会员，十年大会员，百年大会员',
               existing_comment='vip等级（普通用户，月度大会员，年度大会员，十年大会员，百年大会员）',
               existing_nullable=True)
    op.alter_column('TAccountInfo_DashBoardInfo', 'dashboard_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'TAccountInfo',
        existing_comment='账户id，自增主键',
        schema=None
    )
    op.alter_column('TAccountInfo', 'account_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_comment='账户id，自增主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAccountDetailInfo', 'account_detail_info_id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('TAccountBiliWhisperMsg', 'msg_key',
               existing_type=sa.BIGINT(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('SequelizeMeta')
    # ### end Alembic commands ###
